apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: sampleapp
  name: sampleapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sampleapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sampleapp
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
         - containerPort: 80
