apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: sampleapp
  name: sampleapp
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: sampleapp
  type: LoadBalancer
status:
  loadBalancer: {}
